# Generated by Django 4.2.1 on 2023-06-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('img', models.URLField(blank=True, null=True)),
                ('location', models.URLField()),
                ('sockets', models.BooleanField()),
                ('toilet', models.BooleanField()),
                ('wifi', models.BooleanField()),
                ('telephone', models.BooleanField()),
                ('seats', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
        ),
    ]
